import { typeList } from '../type/businessType.ts'
import { BusinessSeedEntry } from './business.ts'

export const clothingList: BusinessSeedEntry[] = [
  {
    id: 'clothing-1',
    name: '戈美其(东山步行街店)',
    email: '',
    address: '南京市江宁区东山街道竹山路59号(上元大街和竹山路交汇处)南京江宁万达广场B1层',
    type: typeList.服装,
    contact: '15851868101',
    rating: null,
    latitude: 31.952718,
    longitude: 118.844754,
    otherInfo: null,
    imageBase64: null,
    description: null
  },
  {
    id: 'clothing-2',
    name: 'MLB&AC(东山步行街店)',
    email: '',
    address: '南京市江宁区步行街小区',
    type: typeList.服装,
    contact: '',
    rating: null,
    latitude: 31.952775,
    longitude: 118.845127,
    otherInfo: null,
    imageBase64: null,
    description: null
  },
  {
    id: 'clothing-3',
    name: '乔丹体育(步行街小区店)',
    email: '',
    address: '南京市江宁区上元二街216号(东山地铁站3号口步行120米)',
    type: typeList.服装,
    contact: '025-51196861',
    rating: null,
    latitude: 31.952824,
    longitude: 118.845069,
    otherInfo: null,
    imageBase64: null,
    description: null
  },
  {
    id: 'clothing-4',
    name: '哎町(步行街小区店)',
    email: '',
    address: '南京市江宁区东山步行街上元二街305号',
    type: typeList.服装,
    contact: '18061883199',
    rating: null,
    latitude: 31.952881,
    longitude: 118.845449,
    otherInfo: null,
    imageBase64: null,
    description: null
  },
  {
    id: 'clothing-5',
    name: '都市丽人(步行街小区店)',
    email: '',
    address: '南京市江宁区东山步行街260号都市丽人',
    type: typeList.服装,
    contact: '',
    rating: null,
    latitude: 31.952993,
    longitude: 118.845866,
    otherInfo: null,
    imageBase64: null,
    description: null
  },
 {
    id: 'clothing-6',
    name: '鸿星尔克(步行街小区店)',
    email: '',
    address: '南京市江宁区上元二街288号(东山地铁站3号口步行220米)',
    type: typeList.服装,
    contact: '15162934873',
    rating: null,
    latitude: 31.953076,
    longitude: 118.846087,
    otherInfo: null,
    imageBase64: null,
    description: null
  },
  {
    id: 'clothing-7',
    name: '裤之都•浅悦(东山步行街店)',
    email: '',
    address: '南京市江宁区上元二街284号(东山地铁站3号口步行230米)',
    type: typeList.服装,
    contact: '13245839886',
    rating: null,
    latitude: 31.9531,
    longitude: 118.846201,
    otherInfo: null,
    imageBase64: null,
    description: null
  },
  {
    id: 'clothing-8',
    name: '贵人鸟(东山步行街店)',
    email: '',
    address: '南京市江宁区步行街小区)',
    type: typeList.服装,
    contact: '',
    rating: null,
    latitude: 31.953133,
    longitude: 118.84618,
    otherInfo: null,
    imageBase64: null,
    description: null
  },
  {
    id: 'clothing-9',
    name: '爱依服(步行街小区店)',
    email: '',
    address: '南京市江宁区东山步行街290号',
    type: typeList.服装,
    contact: '025-52112181',
    rating: null,
    latitude: 31.953138,
    longitude: 118.84633,
    otherInfo: null,
    imageBase64: null,
    description: null
  },
  {
    id: 'clothing-10',
    name: '回力(步行街小区店)',
    email: '',
    address: '南京市江宁区步行街小区',
    type: typeList.服装,
    contact: '',
    rating: null,
    latitude: 31.953152,
    longitude: 118.846524,
    otherInfo: null,
    imageBase64: null,
    description: null
  },
]