import { typeList } from '../type/businessType.ts'
import { BusinessSeedEntry } from './business.ts'

export const supermarketList: BusinessSeedEntry[] = [
  {
    id: 'supermarket-1',
    name: '百世邻里(上坊店)',
    email: '',
    address: '南京市江宁区东山街道上坊天云小区北区9幢101',
    type: typeList.超市,
    contact: '13809049458',
    rating: null,
    latitude: 31.961942,
    longitude: 118.884253,
    otherInfo: null,
    imageBase64: null,
    description: null
  },
  {
    id: 'supermarket-2',
    name: '汇盟源超市(青麓上居店)',
    email: '',
    address: '南京市江宁区武成路68号青麓上居',
    type: typeList.超市,
    contact: '13809049458',
    rating: null,
    latitude: 31.961581,
    longitude: 118.889949,
    otherInfo: null,
    imageBase64: null,
    description: null
  },
  {
    id: 'supermarket-3',
    name: '北京联华(新塘步行街店)',
    email: '',
    address: '南京市江宁区天云小区北区东北门旁',
    type: typeList.超市,
    contact: '',
    rating: null,
    latitude: 31.962249,
    longitude: 118.883982,
    otherInfo: null,
    imageBase64: null,
    description: null
  },
  {
    id: 1,
    name: '联品优选(玖峰兰庭店)',
    email: '1',
    address: '南京市江宁区瑞宁路与万安南路交叉口东100米',
    type: typeList.超市,
    contact: '1',
    rating: null,
    latitude: 31.96211,
    longitude: 118.881618,
    otherInfo: null,
    imageBase64: null,
    description: null
  },
  {
    id: 2,
    name: '购好生活超市(祈泽佳苑店)',
    email: '',
    address: '南京市江宁区东山街道祈泽佳苑9幢一楼102-105室',
    type: typeList.超市,
    contact: '',
    rating: null,
    latitude: 31.967829,
    longitude: 118.877457,
    otherInfo: null,
    imageBase64: null,
    description: null
  },
  {
    id: 'supermarket-3',
    name: '芙蓉兴盛便利超市(云靖花园店)',
    email: '',
    address: '南京市江宁区东山街道龙昌路7号云靖花园',
    type: typeList.超市,
    contact: '',
    rating: null,
    latitude: 31.964637,
    longitude: 118.878571,
    otherInfo: null,
    imageBase64: null,
    description: null
  },
  {
    id: 'supermarket-4',
    name: 'LAWSON罗森(云靖花园店)',
    email: '',
    address: '南京市江宁区龙昌路7号云靖花园店',
    type: typeList.便利店,
    contact: '18851949091',
    rating: null,
    latitude: 31.964545,
    longitude: 118.878288,
    otherInfo: null,
    imageBase64: null,
    description: null
  },
  {
    id: 14,
    name: '华润苏果',
    email: '',
    address: '',
    type: typeList.超市,
    contact: '',
    rating: null,
    latitude: 31.95837,
    longitude: 118.864491,
    otherInfo: null,
    imageBase64: null,
    description: null
  },
  {
    id: 19,
    name: '苏果生活超市(天元吉第城店)',
    email: '',
    address: '南京市江宁区湖山路369号天元吉第城商业12幢102-104号',
    type: typeList.超市,
    contact: '025-51839771 18795980586',
    rating: null,
    latitude: 31.949694,
    longitude: 118.875626,
    otherInfo: null,
    imageBase64: null,
    description: null
  },
  {
    id: 'supermarket-4',
    name: '樽之源百货超市(融侨观榕华府店)',
    email: '',
    address: '南京市江宁区龙昌路50号融侨观榕华府',
    type: typeList.超市,
    contact: '',
    rating: null,
    latitude: 31.965559,
    longitude: 118.879255,
    otherInfo: null,
    imageBase64: null,
    description: null
  },
  {
    id: 'supermarket-5',
    name: '岗山超市',
    email: '',
    address: '南京市江宁区天云南街35号',
    type: typeList.超市,
    contact: '13675191318',
    rating: null,
    latitude: 31.95626,
    longitude: 118.88191,
    otherInfo: null,
    imageBase64: null,
    description: null
  },
]